### PR TITLE
Login and Health screens

### PR DESCRIPTION
**Pull request by vermpat**
Added login screen with a remember functionality. You dont need to add the username, password and host to the python call anymore.

Health status for the switches is also pulled and displayed in a tab of the main screen.

### CODE REVIEW

**Comment by roeles** [comment]
Leuk! Onlangs iets gehad, dat de health interessant is?

**Review by jaccovanschaik — COMMENTED** [review]
- The login window is much larger than it needs to be. Maybe do it as a separate popup window?
- I would prefer it if the error box in the login window goes to the bottom of the window.
- When an error message is shown it is unclear if it is a new error or a previous one. Could be solved by making it a scrollable widget and adding a line for every error (possibly with a timestamp).
- Due to the catch-all "except" on line 227 of NewGui.pyw *every* error is reported as a "Cannot find host" error, which is highly misleading (well, it misled me anyway).
- On my system at least, "ICMP messages" (i.e. ping) "can only be send from processes running as root." This seems to be a pyping limitation because command line pings work fine for me. Does pyping work for you?
- The initial tab when started is the Health tab (because the .ui file was saved with this tab open). This should probably be the Ports tab.
- I do like the contents of the Health tab though. Looks nice.
- I'm getting multiple failures because the program tries again and again to connect to the same unavailable switches (this may be an existing issue). We should probably skip those once we know they're unavailable.

**Comment by vermpat** [comment]
See the commit.
The multiple failures is indeed an existing issue, please make an Issue about this, i will look into fixing it.
The ping problem is indeed a limitation for PyPing. I have not been able to find an alternative for this.

If the other problems have been fixed, i will merge this pull request next week.

**Comment by jaccovanschaik** [comment]
Yes, please merge. There are a few issues that I'd like to investigate further but no show stoppers.

**Pull request merged**
