### PR TITLE
Add script to search for IPs

### PR DESCRIPTION
**Pull request by roeles**
This script should search for IPs.
However, there is no definite answer, so I include the "uncertainty" for each port. This is the total number of MAC addresses seen on each port. The port with the least "uncertainty" is probably the one, but we have no means to be sure.
This script should allow one to write a web-based script to find IPs from a browser.

Please review the code and/or determine if the script is suitable for usage.

### CODE REVIEW

**Review by vermpat — CHANGES_REQUESTED** [review]
Would it be possible to sort the results by uncertainty?
The list of results is also very big, maybe it is possible to have a cutoff value (for instance everything more than 100 above the lowest result automatically filtered out)

**Comment by roeles** [comment]
How about I sort it and output it in valid JSON? Then you can decide where to cut the output.

**Review by vermpat — APPROVED** [review]
This fix works properly, and the amount of results is decreased by a lot and therefore more useful.

**Comment by roeles** [comment]
Thanks, I'm also going to include the port description (which contains the patch-id).
Should be useful, I think.

**Pull request merged**
