### PR TITLE
Add remote span tool

### PR DESCRIPTION
**Pull request by roeles**
Add a remote span tool, for adding and removing remote span session

### CODE REVIEW

**Comment by vermpat** [comment]
This looks good.
Only thing i would like to request is a method to get the current active rspan sessions.
Do you think this would be possible?

**Comment by roeles** [comment]
Please specify what information you would like to see.
It is perhaps possible, but I can likely only give raw output of configurations.

**Comment by roeles** [comment]
@vermpat: Please test the latest version

**Review by vermpat — APPROVED** [review]
Works as intended. The list is very usable to find the current rSPAN sessions running.
I will play a bit more with it tomorrow, but have not run into any problems thus far.

**Comment by vermpat** [comment]
It seems that the session numbers dont quite match up.
If i create an rSpan session with no. 2 like this:
python remote_span.py username password source_switch source_port target_switch target_port 2

it gives me this notice:
Removing all references to Remote SPAN session 3 on vlan 2

after getting the list, it shows as monitor_session 3. When deleting this session (3) it wont work

**Comment by roeles** [comment]
Try using a rspan vlan number, as the usage output indicates.

**Comment by vermpat** [comment]
Would it not make more sense to include that vlan number in the listing then, instead of the session id?

**Comment by roeles** [comment]
It would, will try to fix that.

**Comment by roeles** [comment]
@vermpat: Please see if this works.

**Comment by vermpat** [comment]
@roeles It looks like you replaced the destination port with the vlan number. Is it possible to add the vlan number as a separate variable? As it is also useful to know the switchport on the destination switch where the rspan ends up.

**Comment by roeles** [comment]
I have to parse output per line.
My input looks like this on one switch:
-  `monitor session 1 source interface Gi1/0/42`
-  `monitor session 1 destination remote vlan 1`
and then on the other:
-  `monitor session 1 destination interface Gi1/0/1`
-  `monitor session 1 source remote vlan 1`

So I think this is the best I can do. I cannot connect the output from multiple switches easily in my software. I suggest you do that.

**Comment by roeles** [comment]
@vermpat: updated network_overview.py. Please test

**Comment by vermpat** [comment]
@roeles I have tested it again, and it seems to work properly now. appearantly there was something wrong before.
I'm ok with merging at this point as the function is working properly. 
In the meantime i will create a webpage to make the handling of remote spans easier.

**Pull request merged**
